on: [ push ]

jobs:
  First-Job:
    runs-on: macos-latest
    name: Github Composite Actions !!!dfdfffjsdhfg sdhfg djfhds

    steps:
      - id: triggeringId
        #uses: rogeruiz22/odoafRepo-friday27-950@master
        uses: Oktana/LWC-Incubator-Automation@v01
        with:
          entrada1: 'rogeruiz22/odoafRepo-friday27-950'
          entrada2: 'master'
